# Generated by Django 5.0 on 2024-05-01 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_is_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='is_saved',
        ),
    ]
