# Generated by Django 5.0 on 2024-05-02 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userdetials_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetials',
            name='cycle_length',
            field=models.IntegerField(default=28),
        ),
        migrations.AddField(
            model_name='userdetials',
            name='last_men_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetials',
            name='next_men_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetials',
            name='period_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetials',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
