# Generated by Django 5.0 on 2024-05-02 20:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userdetials_cycle_length_userdetials_last_men_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetials',
            new_name='UserDetial',
        ),
    ]
